### ISSUE TITLE
Install flash-attention failed

### ISSUE THREAD

**Issue by sdfasfsdfasfasafd** [ROCm/flash-attention#80]
I follow the by this link: https://rocm.blogs.amd.com/artificial-intelligence/flash-attention/README.html

I install it in the docker and follow this link:https://rocm.docs.amd.com/projects/install-on-linux/en/develop/install/3rd-party/pytorch-install.html

Here is the Error info:

Failed to build flash_attn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (flash_attn)

**Comment by evshiron** [comment]
Which branch are you using?

**Comment by sdfasfsdfasfasafd** [comment]
> Which branch are you using?
> 
> For Navi31, you might want to follow this thread:
> 
> * [RDNA3 support #27](https://github.com/ROCm/flash-attention/issues/27)
> 
> Or use a Triton-based implementation.

both navi_support and main have tried

**Comment by sdfasfsdfasfasafd** [comment]
> I tried these steps in WSL, and it compiled successfully:
> 
> ```shell
> git clone https://github.com/ROCm/flash-attention
> cd flash-attention
> git checkout howiejay/navi_support
> 
> python3 -m venv venv
> source venv/bin/activate
> 
> pip3 install cmake ninja wheel packaging
> # install a working torch, a custom one for wsl is used in my case
> pip3 install torch --index-url https://download.pytorch.org/whl/rocm6.1
> 
> python3 setup.py bdist_wheel
> # and you get a `flash_attn*.whl` in `dist/`
> ```

I tried it too, but also the Error is as the same as I said "use python setup.py install" on the top

**Comment by evshiron** [comment]
Could you provide a complete log?

**Comment by sdfasfsdfasfasafd** [comment]
> Could you provide a complete log?

[install.log](https://github.com/user-attachments/files/16869267/install.log)

thank you

**Comment by evshiron** [comment]
Seems like a network problem?

**Comment by sdfasfsdfasfasafd** [comment]
> Seems like a network problem?

thanks a lot. I have change to the best proxy,  if still is the network problem, I have no way.o(╥﹏╥)o

**Comment by evshiron** [comment]
```
Submodule 'csrc/composable_kernel' (https://github.com/ROCm/composable_kernel.git) registered for path 'csrc/composable_kernel'
Cloning into '/download/flash-attention/csrc/composable_kernel'...
fatal: unable to access 'https://github.com/ROCm/composable_kernel.git/': Could not resolve host: github.com
fatal: clone of 'https://github.com/ROCm/composable_kernel.git' into submodule path '/download/flash-attention/csrc/composable_kernel' failed
```

You should fix this.

**Comment by sdfasfsdfasfasafd** [comment]
> ```shell
> python3 setup.py bdist_wheel
> ```

also the same error.
[install1.log](https://github.com/user-attachments/files/16870515/install1.log)

**Comment by evshiron** [comment]
Run these steps from scratch (new shell and new location):

* https://github.com/ROCm/flash-attention/issues/80#issuecomment-2328438457

**Comment by nktice** [comment]
> Run these steps from scratch (new shell and new location):
> 
>     * [Install flash-attention failed #80 (comment)](https://github.com/ROCm/flash-attention/issues/80#issuecomment-2328438457)

It seems worth noting that flash-attention version is 2.0.4 
a version so old that's basically useless for lots of programs, 
as that one predates a lot of major changes newer software needs.

**Comment by sancspro** [comment]
Facing the same issue:
RuntimeError: Error compiling objects for extension

I think howiejay/navi_support version is not compatible with ROCM 6.2 which is what I run now. 

Another thing I noticed is ROCM 6.2 needs Pytorch nightly (meant for ROCM 6.2), older Pytorch versions are causing some issues. Pytorch I'm using:
`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.2/`

**Comment by githust66** [comment]
> Which branch are you using?
> 
> For Navi31, you might want to follow this thread:
> 
> * [RDNA3 support #27](https://github.com/ROCm/flash-attention/issues/27)
> 
> Or use a Triton-based implementation.

torch.__version__  = 2.5.1+rocm6.2

Follow this to report the error
`
Traceback (most recent call last):
  File "/root/flash-attention/setup.py", line 331, in <module>
    validate_and_update_archs(archs)
  File "/root/flash-attention/setup.py", line 131, in validate_and_update_archs
    assert all(
AssertionError: One of GPU archs of ['gfx1100'] is invalid or not supported by Flash-Attention
`
![image](https://github.com/user-attachments/assets/e17c4f3a-fdbf-4cc2-915f-9879b2feae57)

**Comment by johnnynunez** [comment]
> > Which branch are you using?
> > For Navi31, you might want to follow this thread:
> > 
> > * [RDNA3 support #27](https://github.com/ROCm/flash-attention/issues/27)
> > 
> > Or use a Triton-based implementation.
> 
> torch.**version** = 2.5.1+rocm6.2
> 
> Follow this to report the error `Traceback (most recent call last): File "/root/flash-attention/setup.py", line 331, in <module> validate_and_update_archs(archs) File "/root/flash-attention/setup.py", line 131, in validate_and_update_archs assert all( AssertionError: One of GPU archs of ['gfx1100'] is invalid or not supported by Flash-Attention` ![image](https://private-user-images.githubusercontent.com/53259654/388407897-e17c4f3a-fdbf-4cc2-915f-9879b2feae57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0NzE5MDYsIm5iZiI6MTczNTQ3MTYwNiwicGF0aCI6Ii81MzI1OTY1NC8zODg0MDc4OTctZTE3YzRmM2EtZmRiZi00Y2MyLTkxNWYtOTg3OWIyZmVhZTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDExMjY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTQ0YWZhM2UzY2VmMTQ4NGZlODdlZDNkYTg0ZjA3ODM5NGYxYzNkM2FhMzYxOGVlODZlNDBjZTQyMDExNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l9CFK3ipPaOKzPTQA7T0twn8RC0WWWkcf8TJiQGdTe8)

yes because flash attention and xformers, bitsandbytes etc use composable kernels that is not supported really for Radeon...
so there are different instructions MI instinc uses FHA... this is why AMD is moving to UDNA, to unify hardware stack and to rocm 7.0 (unified stack) from ryzen to instinct

**Comment by huanrwan-amd** [comment]
Hi @sdfasfsdfasfasafd , as you may notice, gfx1100 is not supported currently: 
https://github.com/ROCm/flash-attention/blob/6aebd958f2115738da9215e59045c50b4ef8594d/setup.py#L128

**Comment by evshiron** [comment]
A Triton-based FA is included in stable PyTorch 2.6, and it's not marked as experimental.

**Comment by 466867517** [comment]
> > > > > Which branch are you using?
> > > > > For Navi31, you might want to follow this thread:
> > > > > 
> > > > > * [RDNA3 support #27](https://github.com/ROCm/flash-attention/issues/27)
> > > > > 
> > > > > Or use a Triton-based implementation.
> > > > 
> > > > 
> > > > torch.**version** = 2.5.1+rocm6.2
> > > > Follow this to report the error `Traceback (most recent call last): File "/root/flash-attention/setup.py", line 331, in <module> validate_and_update_archs(archs) File "/root/flash-attention/setup.py", line 131, in validate_and_update_archs assert all( AssertionError: One of GPU archs of ['gfx1100'] is invalid or not supported by Flash-Attention` ![image](https://private-user-images.githubusercontent.com/53259654/388407897-e17c4f3a-fdbf-4cc2-915f-9879b2feae57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0NzE5MDYsIm5iZiI6MTczNTQ3MTYwNiwicGF0aCI6Ii81MzI1OTY1NC8zODg0MDc4OTctZTE3YzRmM2EtZmRiZi00Y2MyLTkxNWYtOTg3OWIyZmVhZTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDExMjY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTQ0YWZhM2UzY2VmMTQ4NGZlODdlZDNkYTg0ZjA3ODM5NGYxYzNkM2FhMzYxOGVlODZlNDBjZTQyMDExNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l9CFK3ipPaOKzPTQA7T0twn8RC0WWWkcf8TJiQGdTe8)
> > > 
> > > 
> > > yes because flash attention and xformers, bitsandbytes etc use composable kernels that is not supported really for Radeon... so there are different instructions MI instinc uses FHA... this is why AMD is moving to UDNA, to unify hardware stack and to rocm 7.0 (unified stack) from ryzen to instinct
> > 
> > 
> > So, we can not use until the ROCm v7.0 coming up?
> 
> only amd knows. Only I can know it's that pytorch windows is coming q4 2025 aprox... but well we have now flexattention

Can the Flexattention replace flashattention in the model of Huggingface which use flashattention?

**Comment by sdfasfsdfasfasafd** [comment]
> > > > > Which branch are you using?
> > > > > For Navi31, you might want to follow this thread:
> > > > > 
> > > > > * [RDNA3 support #27](https://github.com/ROCm/flash-attention/issues/27)
> > > > > 
> > > > > Or use a Triton-based implementation.
> > > > 
> > > > 
> > > > torch.**version** = 2.5.1+rocm6.2
> > > > Follow this to report the error `Traceback (most recent call last): File "/root/flash-attention/setup.py", line 331, in <module> validate_and_update_archs(archs) File "/root/flash-attention/setup.py", line 131, in validate_and_update_archs assert all( AssertionError: One of GPU archs of ['gfx1100'] is invalid or not supported by Flash-Attention` ![image](https://private-user-images.githubusercontent.com/53259654/388407897-e17c4f3a-fdbf-4cc2-915f-9879b2feae57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0NzE5MDYsIm5iZiI6MTczNTQ3MTYwNiwicGF0aCI6Ii81MzI1OTY1NC8zODg0MDc4OTctZTE3YzRmM2EtZmRiZi00Y2MyLTkxNWYtOTg3OWIyZmVhZTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDExMjY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTQ0YWZhM2UzY2VmMTQ4NGZlODdlZDNkYTg0ZjA3ODM5NGYxYzNkM2FhMzYxOGVlODZlNDBjZTQyMDExNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l9CFK3ipPaOKzPTQA7T0twn8RC0WWWkcf8TJiQGdTe8)
> > > 
> > > 
> > > yes because flash attention and xformers, bitsandbytes etc use composable kernels that is not supported really for Radeon... so there are different instructions MI instinc uses FHA... this is why AMD is moving to UDNA, to unify hardware stack and to rocm 7.0 (unified stack) from ryzen to instinct
> > 
> > 
> > So, we can not use until the ROCm v7.0 coming up?
> 
> only amd knows. Only I can know it's that pytorch windows is coming q4 2025 aprox... but well we have now flexattention

Can the Flexattention replace flashattention in the model of Huggingface which use flashattention? Or any other way to use the huggingface model with the AMD?
